// Staging host where advisor photos are hosted (production nlmsf.org does not have most of these paths)
const IMG = "https://staging5.nlmsf.org/wp-content/uploads";

export const advisors = [
  { name: "Janai Ascher-Carr, MD", position: "Pathologist", institution: "University of California Davis\nSacramento, CA", img: `${IMG}/2024/03/imagetoScale-1-250x300.jpeg` },
  { name: "Nam Quoc Bui, MD", position: "Sarcoma Medical Oncologist", institution: "Stanford Cancer Institute\nStanford University\nStanford, CA", img: `${IMG}/2022/05/Bigger-Dr-Bui.jpg` },
  { name: "Kenneth Cardona, M.D., FACS", position: "Sarcoma Surgical Oncologist", institution: "Emory Winship Cancer Institute\nAtlanta, GA", img: `${IMG}/2024/03/admin-ajax-2-1.jpeg` },
  { name: "Joseph Carlson, M.D., PhD.", position: "Pathologist", institution: "Keck School of Medicine\nUniversity of Southern California\nLos Angeles, CA", img: `${IMG}/2024/03/Carlson-Photo.jpg` },
  { name: "Priya Chudasama, Ph.D.", position: "Sarcoma Researcher", institution: "German Cancer Research Center", img: "https://nlmsf.org/wp-content/uploads/2025/04/Screenshot-2025-04-20-at-12.33.08%E2%80%AFPM.png" },
  { name: "Elizabeth Davis, M.D.", position: "Sarcoma Medical Oncologist", institution: "Vanderbilt-Ingram Cancer Center\nNashville, TN", img: `${IMG}/2024/03/Dr.-Elizabeth-Davis-1-300x300-1.webp` },
  { name: "Ryan Denu, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "University of Texas\nMD Anderson Cancer Center\nHouston, TX", img: "https://nlmsf.org/wp-content/uploads/2025/08/Ryan-Denu.jpg" },
  { name: "Mihaela Druta, M.D.", position: "Sarcoma Medical Oncologist", institution: "Moffitt Cancer Center and Research Institute\nTampa, FL", img: `${IMG}/2024/03/admin-ajax-1.jpeg` },
  { name: "Chiari Fabbroni, M.D.", position: "Sarcoma Medical Oncologist", institution: "National Cancer Institute of Milan\nMilan, Italy", img: `${IMG}/2024/08/Fabbroni-Photo-1.jpg` },
  { name: "Kristen N. Ganjoo, M.D.", position: "Sarcoma Medical Oncologist", institution: "Stanford Cancer Institute\nStanford University\nStanford, CA", img: `${IMG}/2024/03/admin-ajax-3-1.jpeg` },
  { name: "Suzanne George, M.D.", position: "Sarcoma Medical Oncologist", institution: "Dana-Farber Cancer Institute\nBoston, MA", img: `${IMG}/2024/03/admin-ajax-4-1.jpeg` },
  { name: "Rebecca Gladdy, M.D., Ph.D., FRCSC", position: "Surgical Oncologist", institution: "Princess Margaret and Mount Sinai Hospitals\nToronto, Canada", img: `${IMG}/2024/03/admin-ajax-5-1.jpeg` },
  { name: "Elise Nassif Haddid, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "University of Texas\nMD Anderson Cancer Center\nHouston, TX", img: `${IMG}/2024/03/Dr.-Nassifs-Photo.jpg` },
  { name: "Emine Hatipoglu, M.D.", position: "Sarcoma Medical Oncologist", institution: "The Royal Marsden\nLondon, England", img: `${IMG}/2024/03/Hatipoglu-Photo.jpg` },
  { name: "Matthew Hemming, M.D. Ph.D", position: "Sarcoma Medical Oncologist", institution: "University of Massachusetts\nMemorial Medical Center\nWorcester, MA", img: `${IMG}/2024/03/admin-ajax-6-2.jpeg` },
  { name: "Evita Henderson Jackson, M.D.", position: "Pathologist", institution: "Moffitt Cancer Center and Research Institute\nTampa, FL", img: `${IMG}/2023/10/Evita-Henderson-Jackson-MD-.jpeg` },
  { name: "Robin Jones, M.D.", position: "Sarcoma Medical Oncologist", institution: "The Royal Marsden\nLondon, England", img: `${IMG}/2024/03/Jones-Robin-Photo.jpg` },
  { name: "Brian Kadera, M.D.", position: "Pathologist, Surgical Oncologist", institution: "UCLA Medical Center\nLos Angeles, CA", img: `${IMG}/elementor/thumbs/admin-ajax-8-1-qlrad3ouviym7szp8iguvh5jx892qvz4kmocagvqgc.jpeg` },
  { name: "Anush Kaibasi, M.D.", position: "Radiation Oncologist", institution: "Stanford Cancer Institute\nStanford University\nStanford, CA", img: `${IMG}/2024/03/admin-ajax-9-1.jpeg` },
  { name: "Aparna Kamat, M.D.", position: "Gynecologic Surgical Oncologist", institution: "Houston Methodist Hospital\nHouston, TX", img: `${IMG}/2024/03/admin-ajax-10-1.jpeg` },
  { name: "Bernd Kasper, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "Interdisciplinary Tumor Center\nMannheim, Germany", img: `${IMG}/2024/03/bernd-Kasper-Photo.jpg` },
  { name: "Alexander J. Lazar, M.D., Ph.D.", position: "Pathologist", institution: "The University of Texas\nMD Anderson Cancer Center\nHouston, TX", img: `${IMG}/2024/03/admin-ajax-11-1.jpeg` },
  { name: "Alessandra Maleddu, M.D.", position: "Sarcoma Medical Oncologist", institution: "Anschutz Medical Center\nUniversity of Colorado Health Sciences\nAurora, CO", img: `${IMG}/2024/03/Maleddu-Photo.jpg` },
  { name: "Sujana Movva, M.D.", position: "Sarcoma Medical Oncologist", institution: "Memorial Sloan Kettering Cancer Center\nNew York City, NY", img: `${IMG}/2024/03/admin-ajax-12-1.jpeg` },
  { name: "John Mullinax, M.D.", position: "Surgical Oncologist", institution: "Moffitt Cancer Center and Research Institute\nTampa, FL", img: `${IMG}/2024/03/Mullinax-photo-2-300x300.jpg` },
  { name: "Arash Nagavi, M.D.", position: "Radiation Oncologist", institution: "Moffitt Cancer Center and Research Institute\nTampa, FL", img: `${IMG}/2024/03/admin-ajax-13-1.jpeg` },
  { name: "Scott Okuno, M.D.", position: "Sarcoma Medical Oncologist", institution: "Mayo Clinic\nRochester, MN", img: `${IMG}/2024/03/Scott-Okuno-Photo.jpg` },
  { name: "Seth Pollock", position: "Sarcoma Medical Oncologist", institution: "Robert H. Lurie Cancer Center, Northwestern University\nChicago, Illinois", img: `${IMG}/2024/03/admin-ajax-14-1.jpeg` },
  { name: "Kunal Rai, Ph.D.", position: "Associate Professor of Genomic Medicine", institution: "MD Anderson Cancer Center\nHouston, TX", img: "https://nlmsf.org/wp-content/uploads/2025/06/dr.-rai.png" },
  { name: "Albiruni Razak, MB, MRCPI", position: "Sarcoma Medical Oncologist", institution: "Princess Margaret Cancer Center and Mount Sinai Hospital\nToronto, Canada", img: `${IMG}/2024/03/Razak-Photo-300x300.jpg` },
  { name: "Roberta Sanfilippo", position: "Sarcoma Medical Oncologist", institution: "National Cancer Institute of Milan\nMilan, Italy", img: `${IMG}/2024/03/Sanfilippo-Photo-300x300.jpg` },
  { name: "Scott Schuetze, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "Rogel Cancer Center\nUniversity of Michigan\nAnn Arbor, MI", img: `${IMG}/2024/03/Schuetze-Photo.webp` },
  { name: "Dale Shepherd, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "Taussig Oncology\nCleveland Clinic\nCleveland, OH", img: `${IMG}/2024/03/admin-ajax-15-2.jpeg` },
  { name: "Brittany Siontis, M.D.", position: "Sarcoma Medical Oncologist", institution: "Mayo Clinic\nRochester, MN", img: `${IMG}/2024/03/Sciontis-Photo.jpg` },
  { name: "Neeta Somaiah, M.D.", position: "Sarcoma Medical Oncologist", institution: "University of Texas\nMD Anderson Cancer Center\nHouston, TX", img: `${IMG}/2024/03/admin-ajax-16-1.jpeg` },
  { name: "Brian Van Tine, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "Siteman Cancer Center\nWashington University\nSt. Louis, MO", img: `${IMG}/2024/03/admin-ajax-18-1.jpeg` },
  { name: "Eric Toloza, M.D., Ph.D.", position: "Thoracic Oncology Surgeon", institution: "Moffitt Cancer Center\nTampa, FL", img: `${IMG}/2024/08/Toloza-Photo-New.jpg` },
  { name: "Jonathan Trent, M.D., Ph.D.", position: "Sarcoma Medical Oncologist", institution: "Sylvester Cancer Center\nUniversity of Miami Health System\nMiami, FL", img: `${IMG}/2024/03/admin-ajax-17-1.jpeg` },
  { name: "William Tseng, M.D.", position: "Surgical Oncologist", institution: "Keck Medicine\nUniversity of Southern California\nLos Angeles, CA", img: `${IMG}/2024/03/admin-ajax-19-1-1.jpeg` },
  { name: "Breelyn Wilky, M.D.", position: "Sarcoma Medical Oncologist", institution: "Anschutz Medical Center\nUniversity of Colorado Health Sciences\nAurora, CO", img: `${IMG}/2024/08/Breelyn-Wilky-Photo-300x300.jpg` },
];
