export const ARCHIVED_TRIBUTES: { name: string; fund: string }[] = [
  { name: "Alexander, Cecelia", fund: "In Memory of Cecelia Alexander" },
  { name: "Allen, Mary C.", fund: "The Mary C. Allen Memorial Fund" },
  { name: "Allen, Jr., Richard Barry", fund: "The Richard Barry Allen, Jr. Fund" },
  { name: "Allibone, Debra", fund: "In Loving Memory of Debra Allibone" },
  { name: "Allison, Denise", fund: "Friends of Denise Allison" },
  { name: "Amdor, Nelva", fund: "The Nelva Amdor Research Fund" },
  { name: "Ansara, Karen", fund: "Friends and Family of Karen Ansara Fund" },
  { name: "Anthony, James", fund: "In Memory of James L. Anthony, Ph. D." },
  { name: "Ardery, Edward", fund: "In Honor of Edward Ardery" },
  { name: "Arlein, Gay Ann", fund: "Friends & Family of Gay Ann Arlein Memorial Fund" },
  { name: "Arnold, Marietta", fund: "Friends of Marietta Arnold Fund" },
  { name: "Arzac, Alicia M.", fund: "In Loving Memory of Alicia M. Arzac Memorial Fund" },
  { name: "Aughenbaugh, Linda", fund: "In Loving Memory of Linda Aughenbaugh" },
  { name: "Augurt, Tom", fund: "The Tom Augurt LMS Research Fund" },
  { name: "Bailey, Warren", fund: "The Warren Bailey LMS Research Fund" },
  { name: "Bakst, Ira", fund: "In Memory of Ira Bakst Fund" },
  { name: "Bannock, Jodi", fund: "In Loving Memory of Jodi Bannock Fund" },
  { name: "Barber, Walter", fund: "The Walter Barber LMS Memorial Fund" },
  { name: "Bariski, Jim", fund: "Friends of Jim Bariski" },
  { name: "Bartz, Sue Ann", fund: "In Memory of Sue Ann Bartz" },
  { name: "Beaver, Janie T.", fund: "The Janie T. Beaver LMS Research Fund" },
  { name: "Beckcom, Sandra", fund: "Friends & Family of Sandra Beckcom" },
  { name: "Beckwith, Bob", fund: "In Memory of Bob Beckwith" },
  { name: "Bell, Norma", fund: "In Memory of Norma Bell LMS Research Fund" },
  { name: "Benedict, Richard \"Ben\"", fund: "In Loving Memory of Richard \"Ben\" Benedict Fund" },
  { name: "Benson, Robert E.", fund: "The Robert E. Benson Memorial Fund" },
  { name: "Biagini-Phillips, Melissa", fund: "The Friends & Family of Melissa Biagini-Phillips Fund" },
  { name: "Bieber, John", fund: "In Loving Memory of John Bieber" },
  { name: "Binghi, Mary Ann", fund: "The Friends & Family of Mary Ann Binghi Fund" },
  { name: "Bivens, Sue", fund: "In Memory of Sue Bivens" },
  { name: "Blodgett, Samantha", fund: "Research Fund in Celebration of Samantha Blodgett" },
  { name: "Bochicco, Susan", fund: "The Susan Bochicco LMS Research Fund" },
  { name: "Booth, Diane", fund: "The Diane Booth Fund for LMS Research" },
  { name: "Bouchez, Susan", fund: "In Loving Memory of Susan Bouchez" },
  { name: "Bowser, Michelle Ann Michelfelder", fund: "The Michelle Ann Michelfelder Bowser Memorial Fund" },
  { name: "Brossman, Nancy", fund: "In Loving Memory of Nancy Brossman" },
  { name: "Brown, Christina", fund: "In Memory of Christina Brown Fund" },
  { name: "Brown, Freda", fund: "In Memory of Freda Brown" },
  { name: "Brown, Janet", fund: "The Jane Brown \"Let's Inspire Life\" Fund" },
  { name: "Brown, Ron", fund: "In Memory of Ron Brown" },
  { name: "Bunge, Cynthia", fund: "Friends & Family of Cynthia Bunge Fund" },
  { name: "Burgess, John H.", fund: "The John H. Burgess Research Fund" },
  { name: "Burke-Bedsaul, Geri", fund: "The Geri Burke-Bedsaul Fund" },
  { name: "Burnham, Dawn", fund: "In Memory of Dawn Burnham" },
  { name: "Buschiazzo, Janice", fund: "In Memory of Janice Buschiazzo" },
  { name: "Carnovale, Assunta", fund: "The Assunta Carnovale LMS Memorial Fund" },
  { name: "Chamberlain, Marian", fund: "The Marian Chamberlain Memorial Fund" },
  { name: "Cluff, Elaine", fund: "In Memory of Elaine Cluff" },
  { name: "Cohen-Doyle, Myrna", fund: "Friends & Family of Myrna Cohen-Doyle Fund" },
  { name: "Collins, Brenda", fund: "The Brenda F. Collins Research Fund" },
  { name: "Collins, Christy", fund: "The Friends & Family of Christy Collins Fund" },
  { name: "Collo, Nancy", fund: "In Honor of Nancy Collo for her Strength & Perseverance" },
  { name: "Comintinia, Gina", fund: "In Honor & Support of Gina Comintinia" },
  { name: "Conroy, Carolyn", fund: "In Honor of Carolyn Conroy" },
  { name: "Conroy, Carolyn", fund: "In Memory of Carolyn Conroy" },
  { name: "Cooper, Melanie Diane Mott", fund: "The Melanie Diane Mott Cooper Memorial Fund" },
  { name: "Coronado, Carolyn", fund: "The Carolyn Coronado LMS Memorial Fund" },
  { name: "Copplestone, Sarah", fund: "In Honor & Support of Sarah Copplestone" },
  { name: "Corkhill, Patricia", fund: "In Memory of Patricia Simon Corkhill" },
  { name: "Cowen, Janice", fund: "In Honor of Janice Cowen Fund" },
  { name: "Creviston Sr., David J.", fund: "The David J. Creviston, Sr. Memorial Fund" },
  { name: "Crowhurts, Judi Sansom", fund: "In Memory of Judi Sansom Crowhurts" },
  { name: "Curley, Edna", fund: "In Honor of Edna Curley" },
  { name: "Daniel, Therese Aileene Conway", fund: "In Memory of Therese Aileene Conway Daniel" },
  { name: "Darst, Mindy", fund: "In Friendship & Support of Mindy Darst Fund" },
  { name: "Davis Jr., Harry J.", fund: "In Loving Memory of Harry J. Davis, Jr." },
  { name: "DeCrocer, Gerald", fund: "The Gerald DeCroce LMS Memorial Fund" },
  { name: "Denny", fund: "The Running for Denny Fund" },
  { name: "de Vries, Susan", fund: "In Loving Memory of Susan de Vries Fund" },
  { name: "Dibella, Mary", fund: "The Mary Dibella Fund" },
  { name: "Dobson, Nana", fund: "In Loving Memory of Nana Dobson" },
  { name: "Doebler, Jenine", fund: "In Honor of Jenine Doebler, With Love From Your Friends & Family" },
  { name: "Dorrell, Betty", fund: "Betty Dorrell Memorial Fund" },
  { name: "Dreckmann, John", fund: "In Loving Memory of John Dreckmann" },
  { name: "Driscoll, Mark", fund: "The Mark Driscoll LMS Research Fund" },
  { name: "Dusseau, Doug", fund: "Friends of Doug \"Fuzzy\" Dusseau" },
  { name: "Duvall, Sandra", fund: "Sandra Duvall Moore Memorial Fund" },
  { name: "Edmunds, David", fund: "The David Edmunds Memorial Fund" },
  { name: "Eitington, Ellen", fund: "The Ellen Eitington Fund" },
  { name: "Engen, Michellle", fund: "In Memory of Michelle Engen" },
  { name: "Ennis, Judy", fund: "The Judy Ennis Memorial LMS Research Fund" },
  { name: "Ernest, Prudence E.", fund: "The Prudence E. Ernest LMS Research Fund" },
  { name: "Estoff, Cindy", fund: "In Support of Our Mother- The Cindy Estoff LMS Research Fund" },
  { name: "Evands, Leslie", fund: "The Friends & Family of Leslie Evans Fund" },
  { name: "Everhart, Jan", fund: "The Jan Everhart Memorial LMS Fund" },
  { name: "Faggard, Thelma", fund: "In Memory of Thelma Faggard" },
  { name: "Ferguson, Eileen", fund: "The Eileen Ferguson LMS Research Fund" },
  { name: "Fienman, Karyn B.", fund: "The Karen B. Fienman Fund" },
  { name: "Fischer, Donna", fund: "The Donna Fisher Fund" },
  { name: "Fixel, Joni", fund: "The Friends & Family of Joni Fixel LMS Research Fund" },
  { name: "Fordham, R. David", fund: "In Loving Memory of R. David Fordham" },
  { name: "Fowler, Lee", fund: "The Lee Fowler Memorial Fund" },
  { name: "Fox, Helen", fund: "Memory of Helen Fox" },
  { name: "Frank II, Philip", fund: "Philip Frank, II Memorial Fund" },
  { name: "Freyholtz, Lois", fund: "Memory of Lois Freyholtz" },
  { name: "Frigilana, Barbara", fund: "The Barbara Frigillana LMS Research Fund" },
  { name: "Froling, Diana", fund: "Friends of Diana Froling" },
  { name: "Fulper, Mary", fund: "In Loving Memory of Mary Fulper" },
  { name: "Fyfe, Marie L", fund: "In Loving Memory of Marie L. Fyfe" },
  { name: "Gage, Janet", fund: "The Jane Gage Memorial Fund" },
  { name: "Galvin, Dorothy E.", fund: "In Memory of Dorothy E. Galvin Fund" },
  { name: "Gayder, Nancy", fund: "Cassandra LMS Research Fund" },
  { name: "Gaylor, K.D.", fund: "The K.D. Gaylor LMS Memorial Fund" },
  { name: "Gero, Ricki", fund: "Friends & Family of Ricki Gero Fund" },
  { name: "Giegerich, Donnalyn", fund: "The Donnalyn Giegerich LMS Research Fund" },
  { name: "Gilkerson, Estelle M.", fund: "The Estelle M. Gilkerson Memorial Fund" },
  { name: "Gill, Diana", fund: "Friends of Diana Gill" },
  { name: "Goldberg, Beverly", fund: "In Loving Memory of Beverly Goldberg" },
  { name: "Gomez, Monika", fund: "The Monika Gomez Charitable Trust Fund" },
  { name: "Gordon, Bonnie", fund: "In Loving Memory of Bonnie Gordon" },
  { name: "Greenwell, Barbara", fund: "In Loving Memory of Barbara Greenwell Research Fund" },
  { name: "Greseth, Gayle", fund: "In Loving Memory, Family & Friends of Gayle Greseth" },
  { name: "Grondin, Diane", fund: "The Love Diane LMS Memorial Fund" },
  { name: "Hackett, Cheryl", fund: "In Loving Memory of Cheryl Hackett Fund" },
  { name: "Hamilart, Hobart", fund: "In Memory of Hobart Hamilton" },
  { name: "Hammond, Sonny", fund: "In Memory of Sonny Hammond" },
  { name: "Harkinds, Constance", fund: "The Constance Harkins Fund" },
  { name: "Hanover, Laurie", fund: "In Loving Memory of Laurie Hanover" },
  { name: "Haser, Ellen S.", fund: "Ellen S. Haser Memorial Fund" },
  { name: "Hayward, Chris", fund: "The Chris & Dawn Hayward Wedding Fund" },
  { name: "Hayward, Chris", fund: "Friends & Family of Chris Hayward Fund" },
  { name: "Hazelwood, Beverly Brecling", fund: "In Honor of Beverly Brecling Hazelwood" },
  { name: "Heath, Ann", fund: "Family and Friends of Ann Heath Memorial Fund" },
  { name: "Hedlund O.D., Daniel L.", fund: "The Daniel L. Hedlund, O.D. Memorial Fund" },
  { name: "Hedreen, Nita Gardner", fund: "The Nita Gardner Hedreen Memorial Fund" },
  { name: "Hefferson, Erin S.", fund: "In Memory of Erin S. Hefferson" },
  { name: "Henshall, Helen", fund: "The Helen Henshall Trust" },
  { name: "Hetherington Orland", fund: "In Memory of Orland Hetherington Fund" },
  { name: "Heywood, Lara", fund: "Lara Heywood LMS Research Fund" },
  { name: "Hoag, Nancy", fund: "In Memory of Nancy Hoag" },
  { name: "Hollis, Bernadette", fund: "Bernadette M Hollis LMS Research Fund" },
  { name: "Holmes, \"Tudy\"", fund: "Friends and Family of \"Tudy\" Holmes" },
  { name: "Horan, Joe", fund: "Friends & Family of Joe Horan" },
  { name: "Houston, Ruthie", fund: "In Memory of Ruthie Houston" },
  { name: "Hunt, Marcia", fund: "The Marcia Hunt Memorial Fund" },
  { name: "Hvolbeck, Mary Ann", fund: "In Loving Memory of Rose Trembone" },
  { name: "Hvolbeck, Mary Ann", fund: "In Loving Memory of Mary Ann Hvolbeck LMS Research Fund" },
  { name: "Ingrassia, Elisabeth", fund: "Memory of Elisabeth Ingrassia" },
  { name: "Ingram, Sherry", fund: "The Sherry Ingram Memorial Fund" },
  { name: "Jacobs, Neal C.", fund: "In Loving Memory of Neal C. Jacobs" },
  { name: "Jacobson, Janet C.", fund: "The Janet C. Jacobson Memorial Fund" },
  { name: "Jemelka, Kathy", fund: "Kathy Jemelka Memorial Fund" },
  { name: "Johns, Hattie", fund: "The Friends & Family of Hattie Johns Fund" },
  { name: "Johns, Philip", fund: "The Friends of Philip Johns Fund" },
  { name: "Johnson, Angie", fund: "Friends & Family of Angie Johnson Fund" },
  { name: "Johnson, Jillene", fund: "In Memory of Jillene Johnson Fund" },
  { name: "Johnston, Bob", fund: "In Memory of Bob Johnston" },
  { name: "Johnston, Charles", fund: "The Charles Johnston LMS Memorial Research Fund" },
  { name: "Joly, Maureen", fund: "The Maureen Joly Memorial Fund" },
  { name: "Jones, Deborah Davis", fund: "The Deborah Davis Jones Memorial Fund" },
  { name: "Kahn-Denis, Kathleen B.", fund: "The Kathleen B. Kahn-Denis Memorial Fund" },
  { name: "Kavanaugh, Corinne", fund: "The Corinne Kavanaugh Memorial Fund" },
  { name: "Kehoe, Derek", fund: "In Loving Memory of Derek Kehoe Research Fund" },
  { name: "Kelley, Hanford \"Pete\"", fund: "The Hanford \"Pete\" Kelley Memorial Fund" },
  { name: "Kennedy, Dennis L.", fund: "In Memory of Dennis L. Kennedy" },
  { name: "Khalandi, Jafar", fund: "The Jafar Khalandi Memorial Fund" },
  { name: "Kloss, Lisa", fund: "In Loving Memory of Lisa Rae Kloss" },
  { name: "Kochenderfer, Virginia", fund: "The Virginia Kochenderfer Honorary Fund" },
  { name: "Kreamer, Rhonda", fund: "Friends of Rhonda Kreamer" },
  { name: "Krokstrom, Oksana", fund: "Oksana Krokstrom Research Fund" },
  { name: "Kurtis, Debbie", fund: "In Loving Memory of Debbie Kurtis" },
  { name: "LaDonna", fund: "In Loving Memory of LaDonna" },
  { name: "Lao, David", fund: "Friends & Family of David Lao" },
  { name: "Lash, \"J.D.\"", fund: "The \"J.D\" Lash Memorial Fund" },
  { name: "Lavender, Deb", fund: "The Deb Lavender Memorial LeioMyoSarcoma Research Fund" },
  { name: "Lewis, Barbara", fund: "In Honor of Barbara Lewis, With Love From Your Friends & Family" },
  { name: "Lettow, Christine", fund: "The Christine Lettow Fund" },
  { name: "Lippi, Kathy", fund: "In Loving Memory Of Kathy Lippi" },
  { name: "Lloyd, Patti", fund: "The Patti Lloyd Tri4 Awareness Fund" },
  { name: "Lloyd, Richard", fund: "The Richard Lloyd Memorial Research Fund" },
  { name: "Lubic, Patricia Ann", fund: "In Loving Memory of Patricia Ann Lubic Memorial Fund" },
  { name: "Madigan, David", fund: "The David Madigan LMS Research Fund" },
  { name: "Magri, Dolores Helen", fund: "The Dolores Helen Magri Memorial Fund" },
  { name: "Maier, Jerry", fund: "The Heather Maier LMS Fund in Memory of Jerry Maier" },
  { name: "Malek, Wendy A.", fund: "The Wendy A. Malek Fund" },
  { name: "Malek, Wendy A.", fund: "The Wendy A. Malek LMS Research Fund" },
  { name: "Mangiaracina", fund: "The Melissa & Michael Mangiaracina Wedding Fund" },
  { name: "Marie, Frank", fund: "The Frank Marie Memorial Fund" },
  { name: "Marks, Jennifer", fund: "In Loving Memory of Jennifer Marks" },
  { name: "Martin, Joan", fund: "The Joan Martin Memorial Fund" },
  { name: "Martineau, Colleen Kersey", fund: "The Colleen Kersey Martineau Memorial Fund" },
  { name: "Martinez, Deborah", fund: "Friends of Deborah Martinez" },
  { name: "Matthews, Jim", fund: "In Honor of Jim Matthews" },
  { name: "McCarthy, Nancy Taylor", fund: "In Loving Memory of Nancy Taylor McCarthy Fund" },
  { name: "McCollough, Glenis Patricia", fund: "The Glenis Patricia McCollough Memorial LMS Research Fund, In Loving Memory of Glenny Penny" },
  { name: "McDaniel, Debbie", fund: "In Loving Memory of Debbie McDaniel" },
  { name: "McDonough, Betty", fund: "The Betty McDonough Memorial Research Fund" },
  { name: "McGaw, Gloria", fund: "In Memory of Gloria McGaw" },
  { name: "McGuire, Ellen", fund: "The Ellen McGuire Memorial LMS Research Fund" },
  { name: "McGurl, Danny", fund: "The Danny McGurl LMS Research Fund" },
  { name: "McKenzie, Ellen", fund: "In Loving Memory of Ellen McKenzie" },
  { name: "McNamara, Kathy", fund: "In Loving Memory of Kathy McNamara" },
  { name: "McNeil-Smith, Angela", fund: "Friends and Family of Angela McNeil-Smith Fund" },
  { name: "McShane, Mildred", fund: "In Memory of Mildred McShane" },
  { name: "Melitsky, Joan", fund: "In Memory of Joan Melitsky" },
  { name: "Meller, Judy", fund: "The Friends of Judy Meller Fund" },
  { name: "Meszaros, Vic", fund: "The Vic Meszaros LMS Research Fund" },
  { name: "Michaud, Sandra", fund: "In Memory of Sandra Michaud Fund" },
  { name: "Miller, Theresa", fund: "Friends & Family of Theresa Miller" },
  { name: "Milliken, Minot \"Kim\"", fund: "In Memory of Minot \"Kim\" Milliken" },
  { name: "Monaghan, Brian", fund: "The Brian Monagham Fund" },
  { name: "Moore, Betty", fund: "The Betty Moore Memorial Fund" },
  { name: "Moore, Teresa Yancey", fund: "In Honor of Teresa Yancey Moore Fund" },
  { name: "Moran, Kathleen", fund: "In Loving Memory of Kathleen M Moran" },
  { name: "Morgan, Chris", fund: "Friends of Chris Morgan" },
  { name: "Morse, Victoria", fund: "The Vicki Morse Memorial Fund" },
  { name: "Moulds, D Jane", fund: "Slay the LMS Dragon, D Jane Moulds" },
  { name: "Nash, Cynthia", fund: "In Memory of Cynthia Nash" },
  { name: "Neville, Karen A.", fund: "The Karen A. Neville Memorial Fund" },
  { name: "Nicholson, Joanne", fund: "The Joanne Nicholson Fund" },
  { name: "Nowicki, Sue", fund: "Slay the Dragon for Sue Nowicki Fund" },
  { name: "Nussbaum, Frances \"Fritzi\"", fund: "In Memory of Frances \"Fritzi\" Nussbaum" },
  { name: "Nye, Kara", fund: "The Kara Nye LMS Research Fund" },
  { name: "Olsen, Janis", fund: "The Janis Olsen LMS Memorial Fund" },
  { name: "Owens, Jodi", fund: "In Loving Memory of Jodi Owens" },
  { name: "Padma, Atluri", fund: "\"Team Padma\"" },
  { name: "Parker, Linda Pennington", fund: "In Loving Memory of Linda Pennington Parker" },
  { name: "Parker, Marlene", fund: "The Friends & Family of Marlene Parker Fund" },
  { name: "Peck, Kaye", fund: "In Memory of Kaye Peck" },
  { name: "Peipert", fund: "The Peipert Fund" },
  { name: "Pelella, Linda", fund: "In Loving Memory of Linda Pelella" },
  { name: "Pennington, Tami", fund: "Tami Pennington Memorial Fund" },
  { name: "Peragallo, Dawn", fund: "Friends & Family of Dawn Peragallo" },
  { name: "Perry, Jean S.", fund: "The Jean S. Perry Memorial Research Fund" },
  { name: "Peterson, David", fund: "The David Peterson LMS Awareness & Research Fund" },
  { name: "Phillips, Melissa", fund: "The Friends & Family of Melissa Biagini-Phillips Fund" },
  { name: "Piasecki, Linda", fund: "The Friends & Family of Linda Piasecki Fund" },
  { name: "Plochocki, Gail", fund: "In Loving Memory of Gail Plochocki Fund" },
  { name: "Porta, David", fund: "In Memory of David Porta" },
  { name: "Prestine, Kathleen", fund: "The Kathleen Prestine Fund" },
  { name: "Price, Gary", fund: "The Gary R. Price Memorial Fund" },
  { name: "Price, Maurice", fund: "In Loving Memory of Maurice Price LMS Research Fund" },
  { name: "(With Love from your Sue and Your Girls from the UK)", fund: "" },
  { name: "Princess Leora", fund: "The Princess Leora Fund" },
  { name: "Provard, Shyrl", fund: "The Shyrl Provard Memorial Fund" },
  { name: "Puhekker, Eileen", fund: "In Loving Memory of Eileen Puhekker" },
  { name: "Radusinovich, Lynnette Carol", fund: "In Loving Memory of Lynette Carol Radusinovich Research Fund" },
  { name: "Raggio, Phil", fund: "In Loving Memory of Phil Raggio" },
  { name: "Rappaport, David", fund: "The David Rappaport Memorial LMS Research Fund" },
  { name: "Rehder, Amalia \"Molly\" V.", fund: "The Amalia \"Molly\" V. Rehder Memorial Fund" },
  { name: "Riches, Barbara", fund: "The Barbara Riches LMS Memorial Fund" },
  { name: "Rigg, Jo Anne", fund: "In Love & Support of Jo Anne Rigg Fund" },
  { name: "Ritter, Deborah", fund: "The Friends & Family of Deborah Ritter Fund" },
  { name: "Rivera-Alicea, Daisy", fund: "The Daisy Rivera-Alicea \"Esperanza/Hope Fund for LMS Research" },
  { name: "Roby, John T.", fund: "In Memory of John T. Roby" },
  { name: "Robinson, Theresa", fund: "Friends of Theresa Robinson" },
  { name: "Kylene Roth & Robert Sanders Wedding Fund", fund: "In Loving Memory of Derek Kehoe" },
  { name: "Roman, Debra J.", fund: "The Debra J. Roman Memorial Fund" },
  { name: "Rooney, Sue", fund: "The Family & Friends of Sue Rooney Fund" },
  { name: "Rossman, Joanne", fund: "In Loving Memory & Honor of Joanne Rossman" },
  { name: "Rothgeb, BJ", fund: "The BJ Rothgeb Memorial Fund" },
  { name: "Rounding, Betsy", fund: "The Betsy Rounding Fund" },
  { name: "Ryon, Christy", fund: "The Christy Ryon Fund for Research" },
  { name: "Sade, Jenny", fund: "The Jenny Sade Memorial LMS Research Fund" },
  { name: "Samarenda, Baksi", fund: "In Memory of Samarenda Baksi Fund" },
  { name: "Sanchez, Bertha", fund: "In Loving Memory of Bertha Sanchez" },
  { name: "Sapp, Kay", fund: "In Loving Memory of Kay Sapp" },
  { name: "Saunders-Files, Ardeth", fund: "Friends of Ardeth Saunders-Files" },
  { name: "Schmidt, Phyllis", fund: "The Friends & Family of Phyllis Schmidt" },
  { name: "Schriner, Michael", fund: "The Michael Schriner Sarcoma Research Fund" },
  { name: "Schwartz, Joseph Barry", fund: "The Joseph Barry LMS Research Fund" },
  { name: "Scorza, Deborah Anne", fund: "The Deborah Anne Scorza Fund for LMS Research" },
  { name: "Seitel, Karen", fund: "The Karen Seitel LMS Research Fund" },
  { name: "Selzer", fund: "The Suzanne and Maz Selzer Fund" },
  { name: "Seprak, Marka", fund: "The Marka Seprak Memorial Fund" },
  { name: "Shealy, Jeanie", fund: "The Jeanie Shealy Memorial Fund" },
  { name: "Sibert, Suzanne", fund: "In Loving Memory of Suzanne Sibert" },
  { name: "Siegel, Suzie", fund: "Friends of Suzie Siegel" },
  { name: "Siegriest, Nancy", fund: "Nancy Siegriest Memorial Fund" },
  { name: "Sikoryak-Aurori", fund: "In Loving Memory of Jacqueline Sikoryak-Aurori" },
  { name: "Simons, Debra A.", fund: "The Debra A. Simmons LMS Research Fund" },
  { name: "Simpson, Barbara Flower", fund: "The Barbara Flower Simpson Memorial Fund" },
  { name: "Simpson, Seth", fund: "In Loving Memory of Seth Simpson" },
  { name: "Siragusa, Judith", fund: "In Loving Memory of Betsy Slate" },
  { name: "Siroshton, Phyllis", fund: "In Memory of Phyllis Siroshton" },
  { name: "Snow, Katrina", fund: "In Support of Katrina Snow" },
  { name: "Speyer, Patricia", fund: "Friends & Family of Patricia (Pat) Speyer Fund" },
  { name: "Spillman, Ted", fund: "In Memory of Ted Spillman" },
  { name: "Squires, George", fund: "In Fond Memory of George Squires" },
  { name: "Stanfield, Diana", fund: "In Memory of Diana Stanfield" },
  { name: "Stevens, Les", fund: "The Les Stevens LMS Research Fund" },
  { name: "Stewart, Tara", fund: "In Memory of Tara Stewart" },
  { name: "Stieglitz, Betty", fund: "The Friends and Family of Betty Stieglitz LMS Research Fund" },
  { name: "Strahlendorf, Gerry", fund: "The Gerry Strahlendorf Memorial Fund" },
  { name: "Strelbski, Jr. Thomas", fund: "The Thomas Strelbski, Jr. LMS Memorial Research Fund" },
  { name: "Sweetland, Amy", fund: "In Honor of Amy Sweetland Fund" },
  { name: "Swonguer, Maurice", fund: "The Maurice Swonguer LMS Research Fund" },
  { name: "Tam, Raquel Y.", fund: "In Loving Memory of Raquel Y. Tam" },
  { name: "Taylor, Susan M.", fund: "In Loving Memory of Susan M. Taylor" },
  { name: "Tetrault, Jacqueline J.", fund: "The Jacqueline J. Tetrault Fund" },
  { name: "Thomas, Dawn", fund: "The Dawn Thomas Memorial Fund" },
  { name: "Tinucci, Charlotte", fund: "The Charlotte Tinucci LMS Fund" },
  { name: "Titus, Susan", fund: "The Susan Titus Memorial Fund" },
  { name: "Tomchik, John", fund: "In Memory of John Tomchik" },
  { name: "Tornichia, Barbara", fund: "The Barbara Tornichia LMS Research Fund" },
  { name: "Tricca, Louise", fund: "The Louise Tricca LMS Memorial Fund" },
  { name: "Turner, Dale", fund: "The Dale Turner LMS Research Fund" },
  { name: "Turner, Dale", fund: "The Friends and Family of Dale Turner Fund" },
  { name: "Turner, Diane", fund: "In Memory of Diane Turner" },
  { name: "VanDyke, Nina", fund: "The Nina VanDyke Memorial Fund" },
  { name: "Varni, Marlene", fund: "In Loving Memory of Marlene Varni" },
  { name: "Vendetti, Carmen", fund: "In Loving Memory" },
  { name: "Verdugo, Patricia", fund: "In Loving Memory of Patricia Louise Verdugo" },
  { name: "Villano, Julie", fund: "Friends & Family of Julie Villano Fund" },
  { name: "Voll, Sheila", fund: "The Sheila Voll Memorial Fund" },
  { name: "Von Storch, Ken", fund: "The Ken Von Storch Fund" },
  { name: "Ward, David", fund: "David Ward LMS Research Fund" },
  { name: "Warner, Susie", fund: "In Memory of Susie Warner LMS Research Fund" },
  { name: "Webster, William \"Butch\"", fund: "The William \"Butch\" Webster Memorial Fund" },
  { name: "Weisman, LuAnn", fund: "The LuAnn Weisman Memorial Fund" },
  { name: "Werner, Jimmy", fund: "Memory of Jimmy Werner" },
  { name: "Westfield, Crystal", fund: "In Honor of Crystal Westfield" },
  { name: "White, Kieara", fund: "The Kieara A. White LeioMyoSarcoma Research Fund" },
  { name: "Willis, Elaine", fund: "The Elaine Willis LMS Memorial Fund" },
  { name: "Wilson, Glenn", fund: "The Glenn Wilson Fund" },
  { name: "Witmer, Patricia", fund: "In Honor of Patricia \"Pat\" Witmer" },
  { name: "Witte, Antonia", fund: "The Antonia Witte Fund" },
  { name: "Wolder, Gordon Eric, Jr.", fund: "In Memory of Gordon Eric Wolder Jr." },
  { name: "Wright, Russell", fund: "In Memory of Russell Wright" },
];
