export type Testimonial = {
  name: string;
  text: string;
  type: "Research Clinician" | "Patient";
  imageUrl?: string;
  institution?: string;
  homepageDisplay?: boolean;
};

export const clinicianTestimonials: Testimonial[] = [
  {
    name: "Neeta Somaiah, MD",
    text: "\"You are the sweetest. I can see how your compassion and affection positively impact everyone around — across all generations, family, and beyond.\"",
    type: "Research Clinician",
    institution: "MD Anderson Cancer Center",
    imageUrl: "/images/neeta.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. M. Druta",
    text: "\"You are doing so much for so many\" You should be proud of all you have accomplished within the Foundation.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/DR-Durta-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Sant Chawla",
    text: "\"NLMSF is recommended for patients and care givers looking for information on Leiomyosarcoma.\"",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/sant_chawla-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Raphael Pollock",
    text: "The NLMSF provides a vital link between the community, including LMS patients, and the oncology researchers who work tirelessly to help develop a better understanding of this rare disease, with the direct intent to provide sorely needed new therapeutic approaches.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-pollack.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. Roberta Sanfilippo",
    text: "The LMS Roundtable offers the possibility to work with all researchers in the world dedicated to a rare tumor such as LMS. It is an honor to lead the gynecological working group within the NLMSF-SPAEN International Research Roundtable.",
    type: "Research Clinician",
    imageUrl: "https://old.nlmsf.org/wp-content/uploads/2021/03/DrRobertaSanfilippo.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. S. Okuno",
    text: "\"You and Mitch are doing great things in the Foundation, and the Research Roundtable approach to taking things to the next level - this is a good thing!\"",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/ScottOkuno.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Rebecca Gladdy",
    text: "\"I am very much engaged in understanding LMS and hoping to improve care. Annie and Mitch are such great patient advocates which I admire.\"",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/gladdy-rebecca-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. Evan Rosenbaum",
    text: "No better way to advance LMS research - the Roundtable is an achievement to focus on LMS-specific study, and harness scrambled data with different histology's of various sarcomas - a clear signal for this disease type.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-Rosenbaum-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. W. J. Van Houdt",
    text: "I strongly support the NLMSF in their efforts to fight LMS by bringing together world-wide experts - this is a major achievement. Together we are stronger and smarter to fight this disease.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-Van-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. B. Van Tine",
    text: "This is exciting - and the way the Research Roundtable has unfolded is the right approach.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Brian-Van-Tine-MD-PhD.jpg",
    homepageDisplay: false,
  },
  {
    name: "Wantong Yao, PHD",
    text: "Thank you so much for all you have done for us and for LMS research community! We really appreciate!",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/WantongYeoPHD.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Matthew Hemming",
    text: "The essential benefit arising from the Foundation's LMS Roundtable working groups is the opportunity to bring an assembly of researchers and clinicians into a conversation that spans basic research to clinical application. By working together we learn from each other's expertise and build future innovations in LMS patient care.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-Hemming-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Dr. Seth Pollack",
    text: "I love the NLMSF — your signature support advocacy to collaborate with sarcoma centers. LMS is common enough to have had a specific focus initiative, and the NLMSF was many steps ahead of the curve to launch the LMS International Research Roundtable.",
    type: "Research Clinician",
    imageUrl: "https://old.nlmsf.org/wp-content/uploads/2025/10/Seth-Pollack-MD.png",
    homepageDisplay: true,
  },
  {
    name: "Dr. Sebastian Bauer",
    text: "Dear Annie and Mitch — Thank YOU for supporting the cause. You could have just done other stuff. But you choose to fight for this disease. It makes and will further make a difference!",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Sebastian-Bauer-7.jpg",
    homepageDisplay: true,
  },
  {
    name: "Bruce and Beverly Shriver",
    text: "You have made a huge difference in the infrastructure of the NLMSF. You should be proud of what you have done. It is a great Foundation.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Bruce-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Arun Singh",
    text: "I think that the LMS Research Roundtable is a valuable model of bringing clinicians and scientists together to discuss the state of LMS and to develop ideas for pushing the field forward.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-Singh-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Dr. Sandra D'Angelo",
    text: "Annie and Mitch! Thanks for all you do for our patients.",
    type: "Research Clinician",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/Dr-DAngelo-150x150.jpg",
    homepageDisplay: false,
  },
];

export const patientTestimonials: Testimonial[] = [
  {
    name: "Cathy",
    text: "There are no words, Annie, for my gratitude for the work you and Mitch are doing and for the human, loving way you do it, especially now with the government halt on science and research in a time when my daughter needs both so desperately. Your work and caring are lights out there. Never doubt that there are thousands of us sending hope and gratitude to you every day.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Catharine",
    text: "You and Mitch are heroes to our family.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Rebecca",
    text: "\"Thank you, you both are a light where there is fog.\"",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "David Matanic",
    text: "I was diagnosed with LMS just one week ago. Annie Achee and her husband called me and spent about 45 minutes telling me what to expect, what questions to ask and the kind of specialists I would need. It was the most valuable 45 minutes of my life so far. My stress level went down dramatically.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Mary",
    text: "Thank you 100x's over. I have been praying and asking God to send me someone good and kind to help me. Thank you both for all your doing.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Sharon",
    text: "Annie and Mitch are both so special, and make me want to live in this world. I love you guys and NLMSF.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Carolyn",
    text: "Thank you so much for your kind words and your recommendations. Your great passion and commitment got us to the finish line in pulling this Rare Cancer / Sarcoma Webinar program together.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "ED",
    text: "We are all interconnected through one big LIFE, Annie, so it is each of our duty to be mutually supportive. Looking forward to your new and useful insights.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Cathie",
    text: "NLMSF is a wonderful place to help you feel that you are not alone in your LMS journey. You will have access to knowledge, practical tips, resources, and, best of all, contact with others who may be newly diagnosed or long term thrivers.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Hanna",
    text: "Thank you so much for all of your help. In my heart, I am always thinking of you and all of your help to me — a person you never knew, but you worked hard to help.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Edith",
    text: "I feel lucky to have you in my life.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Darlene",
    text: "Dear Annie and Mitch, thank you so very much for your Godly service, direction, precious time, and great knowledge. You have given me a new perspective. You are an awesome duo.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Pamela",
    text: "In 2012, I was diagnosed with leiomyosarcoma, but had never heard of it. Annie Achee has been my life coach through this. If I'm concerned about any treatment, I can call her for guidance. Thank you for your love and support.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Sharon",
    text: "NLMSF is a wonderful place to help you feel that you are not alone in your LMS journey. It is very powerful to know there are others who are many years into their LMS journey, and are leading happy, productive lives.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Evan",
    text: "From the bottom of our hearts, thanks for all the great work that you do for LMS. It is clear that your organization goes above and beyond the call of duty. You are an inspiration to us all.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Michelle",
    text: "I found NLMSF 3 years after my diagnosis of LMS; wish I'd found them sooner. The resources and information they provide is so helpful and the foundation's commitment to furthering research on this disease is vital.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
  {
    name: "Christina",
    text: "Thank you NLMSF and Annie for your support and giving me information to get under the best hospital and doctor care.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: false,
  },
  {
    name: "Emily",
    text: "Thank you so much for your note. You two make our whole family feel enfolded in your care and love. We are so grateful for you.",
    type: "Patient",
    imageUrl: "https://media.nlmsf.org/wp-content/uploads/2021/02/purple-heart-150x150.jpg",
    homepageDisplay: true,
  },
];
