import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "NLMSF Research Projects Funded | National Leiomyosarcoma Foundation",
  description:
    "An overview of the research programs and initiatives funded by the National Leiomyosarcoma Foundation, including the Catalyst Program, SASS, Count Me In, and Early Career Awards.",
};

const programs = [
  {
    id: "catalyst",
    icon: "fas fa-seedling",
    color: "violet",
    label: "Catalyst Program",
    partners: "Drs. Jonathan Fletcher & Keila Torres — SARC",
    amounts: [
      { label: "Young Researcher Travel Award", amount: "$10,000" },
      { label: "Special LMS Project with Dr. Moding", amount: "$25,000" },
    ],
    description: (
      <>
        <p>
          <strong>Keila E. Torres, MD, PhD, MBA, FACS</strong> is the founder and leader of the SARC
          Catalyst Program, co-led with SARC&rsquo;s Chief Scientific Officer{" "}
          <strong>Jonathan Fletcher, MD</strong>. The NLMSF provides $10,000 to support a young
          researcher to attend and present at the meeting, facilitating discussion of small-scale
          research projects with leading investigators.
        </p>
        <p className="mt-3">
          An additional <strong>$25,000</strong> has been committed this year for a special LMS
          Project led by Dr. Moding, expanding the program&rsquo;s focus on leiomyosarcoma-specific
          research initiatives.
        </p>
      </>
    ),
    link: {
      href: "https://sarctrials.org/research/funding-opportunities/catalyst-program/",
      label: "Learn More About the SARC Catalyst Program",
    },
  },
  {
    id: "early-career",
    icon: "fas fa-award",
    color: "indigo",
    label: "NLMSF Early Career Awards",
    partners: "Peer Faculty Recognition Awards",
    amounts: [{ label: "Per award recipient", amount: "$1,400" }],
    description: (
      <>
        <p>
          The NLMSF Early Career Awards — also recognized as <strong>Peer Faculty Recognition
          Awards</strong> — are presented annually to emerging researchers in the leiomyosarcoma
          field. Each award recipient receives <strong>$1,400</strong> to attend the{" "}
          <strong>LMS International Research Roundtable</strong> and present their contributions to
          a selected Workgroup within the Roundtable.
        </p>
        <p className="mt-3">
          This program ensures that the next generation of LMS researchers has a seat at the table
          alongside the world&rsquo;s leading sarcoma investigators, fostering collaboration and
          accelerating discovery.
        </p>
      </>
    ),
    link: {
      href: "/international-research-roundtable",
      label: "Learn More About the LMS International Research Roundtable",
      internal: true,
    },
  },
  {
    id: "count-me-in",
    icon: "fas fa-dna",
    color: "emerald",
    label: "Count Me In — LMS Project",
    partners: "Dr. Suzanne George — Broad Institute / CMI",
    amounts: [
      { label: "Total project data evaluation cost", amount: "$146,000" },
      { label: "NLMSF share (in installments)", amount: "$73,000" },
    ],
    description: (
      <>
        <p>
          The <strong>Count Me In (CMI) LMS Project</strong> is a patient-partnered research
          initiative that has now concluded its data-collection phase. A request has come from{" "}
          <strong>Dr. Suzanne George</strong> for co-funding assistance to evaluate and analyze the
          rich dataset generated by this project.
        </p>
        <p className="mt-3">
          The total cost for this evaluation phase is <strong>$146,000</strong>. The NLMSF has
          committed to covering half of that amount — approximately $73,000 — payable in installment
          payments, ensuring this landmark LMS dataset can be fully analyzed and turned into
          actionable research findings for patients.
        </p>
      </>
    ),
  },
  {
    id: "sass",
    icon: "fas fa-flask",
    color: "amber",
    label: "SASS Program",
    partners: "Strategic Advances in Sarcoma Science",
    amounts: [{ label: "Young investigator award (annual)", amount: "$10,000" }],
    description: (
      <>
        <p>
          The <strong>SASS (Strategic Advances in Sarcoma Science)</strong> Program is designed to
          encourage young investigators to pursue LMS-specific research projects. The NLMSF
          contributes <strong>$10,000 annually</strong> to support one young researcher through this
          competitive program.
        </p>
        <p className="mt-3">
          SASS 2024 was held <strong>September 16–18, 2024</strong>, organized by:{" "}
          <strong>Jonathan Fletcher</strong> (DF/HCC), <strong>Sam Singer</strong> (MSKCC), and{" "}
          <strong>Brigitte Widemann</strong> (NCI).
        </p>
      </>
    ),
    link: {
      href: "https://sarctrials.org/app/uploads/2024/09/SASS2024-Agenda-9.12.2024-943pm.pdf",
      label: "View SASS 2024 Agenda (PDF)",
    },
  },
];

const colorMap: Record<string, { bg: string; border: string; icon: string; badge: string; amount: string; link: string }> = {
  violet: {
    bg: "bg-violet-50",
    border: "border-violet-200",
    icon: "bg-violet-100 text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    amount: "text-violet-700",
    link: "text-violet-700 hover:text-violet-900",
  },
  indigo: {
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    icon: "bg-indigo-100 text-indigo-700",
    badge: "bg-indigo-100 text-indigo-700",
    amount: "text-indigo-700",
    link: "text-indigo-700 hover:text-indigo-900",
  },
  emerald: {
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    icon: "bg-emerald-100 text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    amount: "text-emerald-700",
    link: "text-emerald-700 hover:text-emerald-900",
  },
  amber: {
    bg: "bg-amber-50",
    border: "border-amber-200",
    icon: "bg-amber-100 text-amber-700",
    badge: "bg-amber-100 text-amber-700",
    amount: "text-amber-700",
    link: "text-amber-700 hover:text-amber-900",
  },
};

export default function ResearchProjectsFundedPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-[#f8f9ff] via-[#eef2ff] to-[#f5f3ff]">
      {/* Hero */}
      <section className="bg-gradient-to-br from-[#4338ca] via-[#5b21b6] to-[#6d28d9] text-white py-16 px-6 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 bg-white/10 text-white/90 text-xs font-semibold px-4 py-1.5 rounded-full mb-5 uppercase tracking-widest">
            <i className="fas fa-microscope" aria-hidden />
            Research Initiatives
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold leading-tight mb-4">
            NLMSF Research Projects Funded
          </h1>
          <p className="text-white/80 text-lg max-w-2xl mx-auto">
            An overview of the programs and partnerships the National Leiomyosarcoma Foundation
            funds to accelerate LMS-specific research and support the next generation of investigators.
          </p>
        </div>
      </section>

      {/* Intro panel */}
      <div className="max-w-4xl mx-auto px-6 py-8">
        <div className="bg-white rounded-2xl shadow border border-indigo-100 p-6 text-slate-700 text-base leading-relaxed">
          The NLMSF is committed to funding high-impact research initiatives at every stage — from
          supporting early-career scientists attending leading sarcoma conferences, to co-funding
          large-scale data projects that will shape the future of LMS treatment. Below is a summary
          of the programs the NLMSF actively supports.
        </div>
      </div>

      {/* Program cards */}
      <div className="max-w-4xl mx-auto px-6 pb-16 space-y-8">
        {programs.map((program) => {
          const c = colorMap[program.color];
          return (
            <div
              key={program.id}
              id={program.id}
              className={`rounded-2xl border-2 ${c.border} ${c.bg} shadow-md overflow-hidden`}
            >
              {/* Top accent */}
              <div className={`h-1.5 w-full ${program.color === "violet" ? "bg-gradient-to-r from-violet-400 to-purple-500" : program.color === "indigo" ? "bg-gradient-to-r from-indigo-400 to-blue-500" : program.color === "emerald" ? "bg-gradient-to-r from-emerald-400 to-teal-500" : "bg-gradient-to-r from-amber-400 to-orange-400"}`} />

              <div className="p-6 md:p-8">
                <div className="flex items-start gap-4 mb-5">
                  <div className={`shrink-0 w-12 h-12 rounded-xl ${c.icon} flex items-center justify-center shadow`}>
                    <i className={`${program.icon} text-lg`} aria-hidden />
                  </div>
                  <div>
                    <span className={`inline-block text-xs font-bold px-2.5 py-0.5 rounded-full ${c.badge} uppercase tracking-widest mb-1`}>
                      Funded Program
                    </span>
                    <h2 className="text-xl font-extrabold text-slate-900 leading-snug">
                      {program.label}
                    </h2>
                    <p className="text-sm text-slate-500 mt-0.5">{program.partners}</p>
                  </div>
                </div>

                {/* Funding amounts */}
                <div className="flex flex-wrap gap-3 mb-5">
                  {program.amounts.map((a) => (
                    <div key={a.label} className="bg-white rounded-xl border border-slate-200 px-4 py-2.5 shadow-sm">
                      <p className={`text-xl font-extrabold ${c.amount}`}>{a.amount}</p>
                      <p className="text-xs text-slate-500 mt-0.5">{a.label}</p>
                    </div>
                  ))}
                </div>

                {/* Description */}
                <div className="text-slate-700 text-sm leading-relaxed space-y-2">
                  {program.description}
                </div>

                {/* Link */}
                {program.link && (
                  <div className="mt-5">
                    {program.link.internal ? (
                      <Link
                        href={program.link.href}
                        className={`inline-flex items-center gap-1.5 text-sm font-semibold ${c.link} underline-offset-2 hover:underline`}
                      >
                        <i className="fas fa-arrow-right text-xs" aria-hidden />
                        {program.link.label}
                      </Link>
                    ) : (
                      <a
                        href={program.link.href}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={`inline-flex items-center gap-1.5 text-sm font-semibold ${c.link} underline-offset-2 hover:underline`}
                      >
                        <i className="fas fa-external-link-alt text-xs" aria-hidden />
                        {program.link.label}
                      </a>
                    )}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* CTA */}
      <div className="bg-white border-t border-slate-100 py-12 px-6 text-center">
        <p className="text-slate-500 text-sm max-w-xl mx-auto">
          Interested in applying for NLMSF research funding or learning more about our grant programs?
        </p>
        <div className="mt-4 flex flex-wrap justify-center gap-3">
          <Link
            href="/research-grant-announcement"
            className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm px-5 py-2.5 rounded-xl shadow transition"
          >
            <i className="fas fa-file-alt text-xs" aria-hidden />
            Annual Grant Proposal Announcements
          </Link>
          <Link
            href="/research-funding-2"
            className="inline-flex items-center gap-2 bg-white border border-slate-200 hover:border-indigo-300 text-slate-700 font-semibold text-sm px-5 py-2.5 rounded-xl shadow transition"
          >
            <i className="fas fa-list-alt text-indigo-600 text-xs" aria-hidden />
            View All Funded Projects
          </Link>
        </div>
      </div>
    </main>
  );
}
